---
- name: Deploy Java Build in Tomcat server
- hosts: tomcat
  become: yes
  tasks:
    - name: 'Deploy Java Build in Tomcat server'
      copy:
        dest: '/opt/tomcat10/webapps/ROOT.war'
        src: '/opt/jenkins/workspace/VisOps/t058/sample-java-app/deploy-on-tomcat/webapp/target/webapp.war'
        mode: 0755


    - name: Stop Tomcat service
      service:
        name: tomcat
        state: stopped

    - name: Delete existing ROOT directory
      file:
        path: /opt/tomcat10/webapps/ROOT
        state: absent

    - name: 'start Tomcat service'
      service:
        name: 'tomcat'
        state: started

